# Generated by Django 5.1 on 2024-09-09 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_log_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
